### PR TITLE
Update patchlists for 24.04 release

### PR DESCRIPTION
**Pull request by ashors1**

### CODE REVIEW

**Comment by yhtang** [comment]
Looks like there are [failures](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8748255573/job/24018625027#step:4:70) that look like:
```
AssertionError: Neither rosetta-pax-8748255573-16DP1FSDP1TP1PP_TE/16DP1FSDP1TP1PP_TE/train nor rosetta-pax-8748255573-16DP1FSDP1TP1PP_TE/16DP1FSDP1TP1PP_TE/summaries/train nor rosetta-pax-8748255573-16DP1FSDP1TP1PP_TE/16DP1FSDP1TP1PP_TE/logdir/tensorboard dirs exist
```
while the folder's content looks like
```
16DP1FSDP1TP1PP_TE $ ls
checkpoints  experiment_cls_vars.txt  model_params.txt
```

**Comment by ashors1** [comment]
We see the same failure in the upstream pax tests: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8748255573/job/24017198156#step:4:70, so it looks to me like that problem is unrelated to the new patches

**Comment by ashors1** [comment]
@yhtang both 16DP tests failed with an error that looks like this:
```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: external/xla/xla/service/gpu/runtime/nccl_api.cc:512: NCCL operation ncclGroupEnd() failed: unhandled system error (run with NCCL_DEBUG=INFO for details). Last NCCL warning(error) log entry (may be unrelated) 'Call to ibv_set_ece failed with error Invalid argument errno 22'.
```

**Comment by ashors1** [comment]
I just manually inspected the output from the upstream-pax 16DP test from the XLA reversion PR and it looks like if failed with a similar error: 
```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: external/xla/xla/service/gpu/runtime/nccl_api.cc:512: NCCL operation ncclGroupEnd() failed: unhandled system error (run with NCCL_DEBUG=INFO for details). Last NCCL warning(error) log entry (may be unrelated) '[Proxy Service 15] Failed to execute operation Connect from rank 15, retcode 3'.
```

**Review by terrykong — APPROVED** [review]

**Pull request merged**
