### PR TITLE
Add WAR for XLA NCCL bug causing OOMs

### PR DESCRIPTION
**Pull request by terrykong**
A stopgap for https://github.com/NVIDIA/JAX-Toolbox/issues/346

### CODE REVIEW

**Review by nouiz — APPROVED** [review]
LGTM

**Comment by terrykong** [comment]
The jax ARM build issue still exists. I think it would be preferred to wait for @yhtang's fix for the ARM build before merging this since this should fix many of the CI failures and it would be good to confirm that in the presubmit

**Comment by nouiz** [comment]
If one arch CI pass, I would merge it. This fix stuff, so it is really useful to have it now.
If one arch CI pass, we have a strong enough signal that this small PR is good.
This PR is independent of arch normally.

**Comment by terrykong** [comment]
Triggering manually a full presubmit from jax at an 11/01 commit (last known working nightly was 11/03): https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6801767976

**Comment by terrykong** [comment]
All tests pass except ViT8G2N which is a strict improvement in the CI. We can chase fixing that next.

**Pull request merged**
