### PR TITLE
Cancel CI workflow if it is triggered by a draft PR

### PR DESCRIPTION
**Pull request by yhtang**
Example of the workflow that is cancelled when this draft PR is opened: 
- draft: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7835375902/attempts/1
- rerun after ready for review: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7835375902/attempts/2

### CODE REVIEW

**Comment by yhtang** [comment]
One issue appears to be that we **cannot** rerun a cancelled workflow after flipping the draft mode, as it seems to be tied with the state of the PR at the time the workflow is created. Hence, a dummy commit must be pushed if a PR is marked as ready for review to trigger a full CI.

**Comment by terrykong** [comment]
Is there any reason we can't use: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request ?

Looks like it supports things like:
- ready_for_review
- review_requested

**Comment by terrykong** [comment]
For a future PR, perhaps we can also make use of https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_comment-use-issue_comment

where I imagine you can check the payload for for things like:

```
/ci jax
/ci build
/ci t5x
/ci t5x/test
```

populate a "metadata" step and then each job can run if its selector matches whatever the comment was

and run stages that match the key we expect

**Comment by yhtang** [comment]
> Is there any reason we can't use: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request ?
> 
> Looks like it supports things like:
> 
> * ready_for_review
> * review_requested

That's cool. I just didn't realize it's there :grin:

**Comment by yhtang** [comment]
I ended up using a combination of `on.pull_request.types` and the RESTful API.

**Comment by yhtang** [comment]
Let's merge and see how it works. If not, please give me feedback and I'd be happy to iterate quickly on this.

**Pull request merged**
