### PR TITLE
Bump CUDA version to 12.2.0-devel-ubuntu22.04

### PR DESCRIPTION
**Pull request by andportnoy**

### CODE REVIEW

**Comment by andportnoy** [comment]
Force pushed to fix the version in the commit message.

**Review by yhtang — APPROVED** [review]
LGTM

**Comment by nouiz** [comment]
LGTM

**Comment by yhtang** [comment]
BTW since we always squash merge, you don't have to force push for the purpose of adding new changes.

**Comment by yhtang** [comment]
Looks like our CI cluster needs some update to support CUDA 12.2. I'll try to figure it out shortly.

**Pull request merged**
