### PR TITLE
Bump CUDA to 12.2.0

### PR DESCRIPTION
**Pull request by yhtang**

### CODE REVIEW

**Comment by nouiz** [comment]
@ashors1 @terrykong 
Can you validate that the speed tests didn't regress?

**Comment by yhtang** [comment]
Our CI cluster needs an update to properly test CUDA 12.2 images.

**Comment by terrykong** [comment]
> Our CI cluster needs an update to properly test CUDA 12.2 images.

OOC, will the update be backward compatible for testing our older images?

**Comment by mjsML** [comment]
what is blocking us here? @yhtang @terrykong

**Comment by yhtang** [comment]
I've upgraded the CUDA driver to R535 on the CI cluster.

**Comment by nouiz** [comment]
@terrykong @ashors1 Can we merge this PR?
Do you see any bugs or regression for t5x/pax?

**Comment by terrykong** [comment]
For t5x, to see regressions on the CI, we need this [PR](https://github.com/NVIDIA/JAX-Toolbox/pull/256) by @maanug-nv  to get in to check if there were any regressions with respect to loss/perf

For pax, it looks like the tests for loss/perf ran and there's one failure: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6278073889/job/17053680183?pr=248#step:4:331

@ashors1 is this expected?

**Comment by terrykong** [comment]
@maanug-nv can we make an ephemeral branch with this change and the change in https://github.com/NVIDIA/JAX-Toolbox/pull/256 to make sure t5x hasn't regressed?

**Comment by ashors1** [comment]
> For pax, it looks like the tests for loss/perf ran and there's one failure: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6278073889/job/17053680183?pr=248#step:4:331
> 
> @ashors1 is this expected?

Perf with this change is at least as good as the perf from [yesterday's nightly](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6298101592) in every case. So I don't think there's any evidence that the bump in CUDA version is causing a regression.

**Comment by terrykong** [comment]
Thanks @ashors1 for confirming!

**Comment by nouiz** [comment]
So everything is ready to merge and tomorrow we will have CUDA 12.2 in our nightly?

**Comment by yhtang** [comment]
For T5X, in lieu of #256, my eye-stimate of the tensorboard metrics is consistent with what we previously had. Combined with Anna's confirmation, I think we are good to go.

**Comment by yhtang** [comment]
@nouiz Please 'approve' to indicate that we all agree to merge this PR :grin:

**Comment by terrykong** [comment]
> For T5X, in lieu of https://github.com/NVIDIA/JAX-Toolbox/pull/256, my eye-stimate of the tensorboard metrics is consistent with what we previously had. Combined with Anna's confirmation, I think we are good to go.

For posterity since the check has to be manual until #256 is in:

- [ ] 1P2G: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1P2G%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 1P1G: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1P1G%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 1G2N https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1G2N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 4G1N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F4G1N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 2G2N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F2G2N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 1P4G: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1P4G%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 2G1N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F2G1N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 1G1N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1G1N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 8G1N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F8G1N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 1P8G: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F1P8G%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 4G2N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F4G2N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens
- [ ] 8G2N: https://tensorboard.jax-toolbox.nvidia.com/#scalars&regexInput=(6278073889%7C6298056663)%2F8G2N%2Ftrain&_smoothingWeight=0&tagFilter=seqs_per_second_per_core%7Ccross_ent_loss_per_all_target_tokens

LGTM!

**Review by terrykong — APPROVED** [review]

**Review by nouiz — APPROVED** [review]

**Pull request merged**
