### PR TITLE
Add arm64 image to the Pax nightly build

### PR DESCRIPTION
**Pull request by yhtang**
This will render both the Pax nightlies (`pax:nightly-YYYY-MM-DD`) and the CI builds multi-arch.

### CODE REVIEW

**Comment by nouiz** [comment]
LGTM, but I can't review the details?
I get an error when I try to download the containers on x86:
```
$ docker pull ghcr.io/nvidia/jax-toolbox-internal:6316452742-base-multiarch
Error response from daemon: denied
```
How can I test it?

**Comment by yhtang** [comment]
> LGTM, but I can't review the details? I get an error when I try to download the containers on x86:
> 
> ```
> $ docker pull ghcr.io/nvidia/jax-toolbox-internal:6316452742-base-multiarch
> Error response from daemon: denied
> ```
> 
> How can I test it?

Our workflow already assigned a tag for the image, but it has not been built yet. It will be ready when the build-pax job completes.

**Comment by yhtang** [comment]
This is the multiarch image produced by the workflow: `ghcr.io/nvidia/jax-toolbox-internal:6316452742-pax-multiarch`

**Comment by yhtang** [comment]
Pax MGMN tests all failed due to
```
slurmstepd: error: pyxis:     [ERROR] URL https://ghcr.io/v2/nvidia/jax-toolbox-internal/manifests/6316452742-pax-multiarch returned error code: 404 Not Found
```
There is an incompatibility between the pyxis version available on our CI cluster and the format of the multi-arch manifest. I'll look into it.

**Comment by nouiz** [comment]
LGTM. When the CI pass, you can merge.

**Comment by yhtang** [comment]
Pax CI passed. I'll push one more minor fix for tag naming and then merge.

**Pull request merged**
