### PR TITLE
Fix markdown hyperlink for jax package on frontpage readme

### PR DESCRIPTION
**Pull request by terrykong**

### CODE REVIEW

**Comment by yhtang** [comment]
`ghcr.io/nvidia/jax` automatically redirects to `https://github.com/nvidia/JAX-Toolbox/pkgs/container/jax` if accessed by a browser. Is this causing issues in some situations?

**Review by yhtang — COMMENTED** [review]
ghcr.io/nvidia/jax automatically redirects to https://github.com/nvidia/JAX-Toolbox/pkgs/container/jax if accessed by a browser. Is this causing issues in some situations?

**Comment by terrykong** [comment]
Strange. For me it gets processed as a relative link in the repo on chrome and gets directed to:

https://github.com/NVIDIA/JAX-Toolbox/blob/main/ghcr.io/nvidia/jax

**Comment by terrykong** [comment]
Oh I see what you are saying. Entering `ghcr.io/nvidia/jax` directly into the browser redirects, but I think b/c there's no https?:// URI, it gets interpreted as a relative path

**Review by yhtang — APPROVED** [review]

**Comment by yhtang** [comment]
> Oh I see what you are saying. Entering `ghcr.io/nvidia/jax` directly into the browser redirects, but I think b/c there's no https?:// URI, it gets interpreted as a relative path

I guess this is where GFM's secret sauce backfires :)

**Pull request merged**
