### PR TITLE
bump CUDA version to 12.3.0

### PR DESCRIPTION
**Pull request by yhtang**

### CODE REVIEW

**Comment by yhtang** [comment]
@terrykong @ashors1 Could you please confirm if the T5X/Pax errors are pre-existing?

@nouiz Any tips on the TE test error that also seems to have existed for some time?

**Comment by nouiz** [comment]
I don't remember that kind of TE failure here: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7462032809/job/20305421753?pr=460
@denera Any idea?

**Comment by yhtang** [comment]
> I don't remember that kind of TE failure here: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7462032809/job/20305421753?pr=460 @denera Any idea?
> 
> Note, the TE multi-gpus tests are passing.

The same error showed up in previous nightlies too. This is the earliest failure:
https://github.com/NVIDIA/JAX-Toolbox/actions/runs/7428514648/job/20215944118#step:7:109

**Comment by yhtang** [comment]
Filed TE issue: https://github.com/NVIDIA/TransformerEngine/issues/598

However, the issue seems to be pre-existing even at CUDA 12.2.

**Comment by ashors1** [comment]
> @terrykong @ashors1 Could you please confirm if the T5X/Pax errors are pre-existing?

Yes, confirmed that the T5X and Pax errors are pre-existing

**Comment by yhtang** [comment]
The TE issue is due to the test not being skipped in single-node test, so not related to this PR.

**Comment by yhtang** [comment]
I'll merge this PR as the CI failures are either pre-existing or unrelated.

**Pull request merged**
