### PR TITLE
Create Docker manifest V2 schema 2 images in CI

### PR DESCRIPTION
**Pull request by yhtang**
These images will be located in the `ghcr.io/nvidia/jax-toolbox-retrofit` repo.

Example images created:
- [6584312905-jax-toolbox-internal-6584312905-pax-multiarch-linux-amd64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139560350?tag=6584312905-jax-toolbox-internal-6584312905-pax-multiarch-linux-amd64)
- [6584312905-jax-toolbox-internal-6584312905-pax-multiarch-linux-arm64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139560297?tag=6584312905-jax-toolbox-internal-6584312905-pax-multiarch-linux-arm64)
- [6584312905-jax-toolbox-internal-6584312905-upstream-pax-multiarch-linux-arm64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139560221?tag=6584312905-jax-toolbox-internal-6584312905-upstream-pax-multiarch-linux-arm64)
- [6584312905-jax-toolbox-internal-6584312905-upstream-pax-multiarch-linux-amd64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139560133?tag=6584312905-jax-toolbox-internal-6584312905-upstream-pax-multiarch-linux-amd64)
- [6584312905-jax-toolbox-internal-6584312905-jax-multiarch-linux-amd64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139560018?tag=6584312905-jax-toolbox-internal-6584312905-jax-multiarch-linux-amd64)
- [6584312905-jax-toolbox-internal-6584312905-jax-multiarch-linux-arm64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139559937?tag=6584312905-jax-toolbox-internal-6584312905-jax-multiarch-linux-arm64)
- [6584312905-jax-toolbox-internal-6584312905-base-multiarch-linux-amd64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139559812?tag=6584312905-jax-toolbox-internal-6584312905-base-multiarch-linux-amd64)
- [6584312905-jax-toolbox-internal-6584312905-base-multiarch-linux-arm64](https://github.com/orgs/NVIDIA/packages/container/jax-toolbox-retrofit/139559652?tag=6584312905-jax-toolbox-internal-6584312905-base-multiarch-linux-arm64)

### CODE REVIEW

**Comment by terrykong** [comment]
This is to address https://github.com/NVIDIA/JAX-Toolbox/issues/310 ?

**Comment by yhtang** [comment]
Yes, together with https://github.com/NVIDIA/JAX-Toolbox/pull/321.

Also, #310 is actually already documented in our landing page README:
image

**Comment by nouiz** [comment]
If it works no objection.

**Comment by yhtang** [comment]
@nouiz Could you please try out the containers that I just updated to the PR description and let me know if they work for you?

**Comment by nouiz** [comment]
> @nouiz Could you please try out the containers that I just updated to the PR description and let me know if they work for you?

It work.

**Pull request merged**
