### PR TITLE
Publishes rosetta CUDA 12.1 and containers for pax and t5x AND containers for nightlies based on jax-pinned images for CUDA 12.1 and 12.2

### PR DESCRIPTION
**Pull request by terrykong**

### CODE REVIEW

**Review by yhtang — COMMENTED** [review]
Will this build arm64 images once #284 is merged?
We probably don't want to build arm64+CUDA12.1 images since they do not work on Grace Hopper.

**Comment by terrykong** [comment]
Oops. You are right. I need to rebase this on #284 and only add the amd64 platform. Will do that now

**Comment by terrykong** [comment]
Done. Launched this run to test: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6436638266

**Comment by terrykong** [comment]
Re-running CI after rebasing on top of the multiarch PR to make sure nothing broke: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6465287847

**Comment by terrykong** [comment]
Ahh, even that build failed. I forgot I haven't cherry-picked @yhtang 's fix for NCCL in 12.1 images

**Comment by yhtang** [comment]
Rerunning agaaain after rebasing with the latest NCCL fix.

https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6466124323

**Comment by terrykong** [comment]
Launched sandbox CI:
* `cuda-121-jax-pin.yaml`: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6487938863
* `cuda-122-jax-pin.yaml`: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6487939518

**Comment by yhtang** [comment]
Rerun on top-of-tree for JAX/XLA after https://github.com/openxla/xla/pull/6305 is merged: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6512759676

**Pull request merged**
