### PR TITLE
Remove version.py before build

### PR DESCRIPTION
**Pull request by olupton**
Workaround for https://github.com/google/jax/issues/18252.

### CODE REVIEW

**Comment by nouiz** [comment]
@DwarKapex can you review?

**Comment by DwarKapex** [comment]
Looks like it's a temporary workaround until the is jax issue #18252 is resolved.

**Review by DwarKapex — APPROVED** [review]

**Review by yhtang — CHANGES_REQUESTED** [review]
@olupton Could you please add a comment to reference [the upstream issue](https://github.com/google/jax/issues/18252)? Also, please remember to revert it once the issue is fixed upstream.

**Comment by olupton** [comment]
> @olupton Could you please add a comment to reference [the upstream issue](https://github.com/google/jax/issues/18252)? Also, please remember to revert it once the issue is fixed upstream.

I think that opening this workaround PR triggered this comment: https://github.com/google/jax/issues/18252#issuecomment-1828285721. I guess we should investigate more. Do you know anything relevant about whether this is expected behaviour or a bug in `pip` @yhtang ?

**Comment by yhtang** [comment]
LGTM. We should be able to rebase and merge this PR after #402 and #404 get merged (for an all-green presubmit CI).

**Comment by olupton** [comment]
https://github.com/google/jax/pull/18746 is merged, so this workaround should be redundant now.

**Pull request closed without merging**
