### PR TITLE
Add 5b pax test with fused attention

### PR DESCRIPTION
**Pull request by ashors1**

### CODE REVIEW

**Comment by terrykong** [comment]
Is it possible to use [matrix.include](https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/workflows/_test_t5x_rosetta.yaml#L225-L244) to simplify the amount of jobs you have?

**Review by terrykong — CHANGES_REQUESTED** [review]
Is it possible to use [matrix.include](https://github.com/NVIDIA/JAX-Toolbox/blob/main/.github/workflows/_test_t5x_rosetta.yaml#L225-L244) to simplify the amount of jobs you have?

**Review by terrykong — DISMISSED** [review]
LGTM. FFTM once CI passes

**Review by yhtang — COMMENTED** [review]
Not an objection to the PR, but I'm a bit concerned that adding more MGMN tests will make the SLURM cluster backlog even worse. We need to discuss a bit on this offline.

**Review by yhtang — APPROVED** [review]

**Pull request merged**
