### PR TITLE
Manifest bump to 2024-04-04 except pax & praxis

### PR DESCRIPTION
**Pull request by gspschmid**
The version bump in https://github.com/NVIDIA/JAX-Toolbox/pull/682, except for pax and praxis, whose versions are taken from https://github.com/NVIDIA/JAX-Toolbox/pull/639

This should hopefully unblock https://github.com/NVIDIA/JAX-Toolbox/pull/681, which requires upgrading jax _beyond_ `0.4.26`.

(Previously tried to base this on #701 instead of #682, but that breaks triton.)

### CODE REVIEW

**Comment by olupton** [comment]
Looking at the paxml patch, it seems like this PR (https://github.com/NVIDIA/JAX-Toolbox/pull/734/files#diff-c1953b1225055d751d89e414d87419ed4d0bb87e3c30fe3b14ff8ae345fb03a9) is doing the same thing as https://github.com/NVIDIA/JAX-Toolbox/pull/682/files#diff-c1953b1225055d751d89e414d87419ed4d0bb87e3c30fe3b14ff8ae345fb03a9, but it should match https://github.com/NVIDIA/JAX-Toolbox/pull/639/files#diff-c1953b1225055d751d89e414d87419ed4d0bb87e3c30fe3b14ff8ae345fb03a9, which is different.

**Comment by gspschmid** [comment]
@olupton I think that's just because the 03-14 bump PR has an older merge base, whereas the this PR and the 04-04 bump PR are based on a main that already includes this commit that happened ~3 weeks ago: https://github.com/NVIDIA/JAX-Toolbox/commit/1ce95e34ff2a337369b54051344bf309a355f06f#diff-c1953b1225055d751d89e414d87419ed4d0bb87e3c30fe3b14ff8ae345fb03a9

**Review by yhtang — APPROVED** [review]
LGTM. Please verify that CI does not produce new errors.

**Comment by gspschmid** [comment]
> Please verify that CI does not produce new errors.
Well, unfortunately it did -- some patch doesn't apply cleanly during the pax build: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8736756450/job/23973387180?pr=734#step:9:582
Will have to take a closer look.

**Comment by terrykong** [comment]
@gspschmid Did you also take the patches from 3/14 for pax/praxis? If not, you'll have to pull those in as well as opposed to using the one from 4/04

**Comment by gspschmid** [comment]
@terrykong Yup, what I did was basically
```
git cherry-pick -n bump-04-04
git reset pax-and-praxis-patches
*modify manifest to keep all changes except for latest_verified_version of paxml and praxis* 
git commit

git cherry-pick -n bump-03-14
git reset anything-but-pax-and-praxis-patches
*modify manifest to keep no changes except for latest_verified_version of paxml and praxis* 
git commit
```

**Comment by olupton** [comment]
We're no longer using this manifest file for the presubmit, so this is outdated.

**Pull request closed without merging**
