### PR TITLE
Adding a bidirectional CKPT converter of TE <-> Pax/T5X

### PR DESCRIPTION
**Pull request by mingxu1067**
Replaces #425.

### CODE REVIEW

**Review by yhtang — APPROVED** [review]

**Comment by terrykong** [comment]
@hemildesai @ashors to validate converter

**Comment by ashors1** [comment]
It might be useful to provide some documentation on how to convert BF16 checkpoints to TE FP8 checkpoints, as IIRC the converter only works OOTB for TE BF16. WDYT @mingxu1067?

**Comment by mingxu1067** [comment]
> It might be useful to provide some documentation on how to convert BF16 checkpoints to TE FP8 checkpoints, as IIRC the converter only works OOTB for TE BF16. WDYT @mingxu1067?

Yes, it currently only works OOTB for TE/BF16 only and requires some hacky trick to make the converted CKPT working for TE/FP8. Agree that adding a documentation would be helpful. For longtem support, I am thinking if we could auto-generate FP8 meta for those CKPTs trained on BF16 to further TE/FP8, then things could be much convenient to users.

**Comment by yhtang** [comment]
@mingxu1067 Do you plan to add the documentation in this PR or in a subsequent one?

**Comment by mingxu1067** [comment]
It would be a subsequent one.

**Comment by ashors1** [comment]
> It would be a subsequent one.

In that case, can we add a relnote to the documentation outlining this limitation?

**Comment by ashors1** [comment]
Another suggestion: Pax expects checkpoints to have the following directory structure: `${checkpoint_dir}/checkpoints/checkpoint_${step}`. If the checkpoints do not have this structure, restoring from the checkpoint will error. The Pax converter writes the flat checkpoint to `$output_path`. Perhaps it would be good to instead write the checkpoint to `${output_path}/checkpoints/checkpoint_${step}` so users can pass `$output_path` directly into pax without manually restructuring the directory.

**Comment by mingxu1067** [comment]
> In that case, can we add a relnote to the documentation outlining this limitation?

Sure, where would the proper place to put the note?

> Another suggestion: Pax expects checkpoints to have the following directory structure: ${checkpoint_dir}/checkpoints/checkpoint_${step}. If the checkpoints do not have this structure, restoring from the checkpoint will error. The Pax converter writes the flat checkpoint to $output_path. Perhaps it would be good to instead write the checkpoint to ${output_path}/checkpoints/checkpoint_${step} so users can pass $output_path directly into pax without manually restructuring the directory.

Will sync with team to schedule this.

**Comment by mingxu1067** [comment]
@hemildesai,
We added an argument `--skip-ln` to support T5 v1.1, please give it a try.

@ashors1,
> In that case, can we add a relnote to the documentation outlining this limitation?
We added a description in README.md to guide the steps to run the converted CKPT with TE + FP8. Please help to review.

> Another suggestion: Pax expects checkpoints to have the following directory structure: ${checkpoint_dir}/checkpoints/checkpoint_${step}. If the checkpoints do not have this structure, restoring from the checkpoint will error. The Pax converter writes the flat checkpoint to $output_path. Perhaps it would be good to instead write the checkpoint to ${output_path}/checkpoints/checkpoint_${step} so users can pass $output_path directly into pax without manually restructuring the directory.
After thinking, could we set output path with the same structure of Pax as a solution, like `--output-path=/your_path_to_output/checkpoints/checkpoint_${step}`?

**Comment by mingxu1067** [comment]
> Yeah, that would work. It might be good to document this as well so users do not run into issues trying to pass the flat checkpoint into Pax.

Sure, I think it might be worth to document for both Pax and T5X. I know the CKPT structure for pax is like `/your_path_to_output/checkpoints/checkpoint_${step}/state`, and what is for T5X?

**Comment by terrykong** [comment]
For T5x it looks like:
`/your_path_to_output/checkpoint_${step}/...`

Here's an example:
```
./checkpoint_144000
./checkpoint_144000/flax_mutables.fp8_meta_collection.encoder.layers_10.attention.qkv.fp8_max
./checkpoint_144000/flax_mutables.fp8_meta_collection.decoder.layers_5.self_attention.qkv.fp8_meta_scale
./checkpoint_144000/flax_mutables.fp8_meta_collection.encoder.layers_21.attention.out.fp8_meta_amax
./checkpoint_144000/flax_mutables.fp8_meta_collection.decoder.layers_13.encoder_decoder_attention.out.fp8_max
./checkpoint_144000/flax_mutables.fp8_meta_collection.decoder.layers_2.encoder_decoder_attention.query.fp8_meta_amax
./checkpoint_144000/flax_mutables.fp8_meta_collection.decoder.layers_13.encoder_decoder_attention.kv.fp8_meta_amax
./checkpoint_144000/flax_mutables.fp8_meta_collection.decoder.layers_18.mlp.fp8_meta_amax
```

**Comment by mingxu1067** [comment]
Done, kindly review README.md and correct me if there are any santence not proper to publish.

**Review by yhtang — APPROVED** [review]

**Comment by ashors1** [comment]
> I know the CKPT structure for pax is like /your_path_to_output/checkpoints/checkpoint_${step}/state

I think it should be `/your_path_to_output/checkpoints/checkpoint_${step}`. If using `/your_path_to_output/checkpoints/checkpoint_${step}/state`, pax also expects metadata which is not present with this converted checkpoint.

**Pull request merged**
