### PR TITLE
Refactor 24.04 fix ngc-release-test workflow

### PR DESCRIPTION
**Pull request by DwarKapex**
Refactor ngc-release-test workflow to correspond to present changes in `24.04-devel` branch:
1. Only JAX and Rosetta PAX are tested using this workflows.

### CODE REVIEW

**Review by yhtang — COMMENTED** [review]
There is no CI run.
Could we manually trigger the NGC release testing workflow to confirm it's working?

**Comment by yhtang** [comment]
> There is no CI run. Could we manually trigger the NGC release testing workflow to confirm it's working?

@DwarKapex Could you please address my comments above?

**Comment by yhtang** [comment]
> There is no CI run. Could we manually trigger the NGC release testing workflow to confirm it's working?

@DwarKapex Just to clarify that we should manually trigger the "NGC release testing" workflow (`ngc-release-testing.yaml`) to verify that it is functional. The presubmit CI (`ci.yaml`) is now running but it does not verify the NGC workflow.

**Comment by yhtang** [comment]
I just found that there is indeed a manual trigger: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8608117056 😁 
However, it looks like a experimental run as most of the jobs in that run were cancelled.

**Comment by DwarKapex** [comment]
> I just found that there is indeed a manual trigger: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8608117056 😁 However, it looks like an experimental run as most of the jobs in that run were cancelled.

Here is an automatic run tirggered externally: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/8610029132

**Review by yhtang — APPROVED** [review]
LGTM!

**Pull request merged**
