### PR TITLE
Adds slurm scripts for t5x and updates t5x instructions to use latest nightlies

### PR DESCRIPTION
**Pull request by terrykong**
SLURM scripts were moved to rosetta outside of t5x since it is inconvenient for an end-user to pull an image just to get sbatch submit scripts.

### CODE REVIEW

**Comment by yhtang** [comment]
I would sweat if I were asked to run these SLURM scripts for the first time 😂 
Is there any way that we can make them more readable and less lengthy?

**Comment by sharathts** [comment]
@yhtang Unfortunately not. These are our minimal and standard slurm scripts used throughout. We use the same ones for all DLE release as well as for MLPerf.

**Review by sharathts — DISMISSED** [review]

**Comment by yhtang** [comment]
At least we can add some comments to document the use/source/rationale of the variables and setup? This would ensure a new user can learn the thinking process behind the script so that they can adapt it rationally.

**Comment by terrykong** [comment]
I plan on improving docs in subsequent PRs.

Once #117 is in, this can be merged

**Review by sharathts — APPROVED** [review]

**Pull request merged**
