### PR TITLE
Optionally publish containers at end of CI

### PR DESCRIPTION
**Pull request by yhtang**
This is the last piece of the work for converging our presubmit and nightly workflows.

After this merges, we will publish the following series of containers:
```
ghcr.io/nvidia/jax:<flavor>
ghcr.io/nvidia/jax:<flavor>-YYYY-MM-DD
ghcr.io/nvidia/jax-mealkit:<flavor>
ghcr.io/nvidia/jax-mealkit:<flavor>-YYYY-MM-DD
```
where `<flavor>` is
- one of {base, jax, pallas, maxtext, levanter, upstream-pax, upstream-t5x, pax, t5x} etc. for `ghcr.io/nvidia/jax`
- one of {jax, pallas, maxtext, levanter, upstream-pax, upstream-t5x, pax, t5x} etc. for `ghcr.io/nvidia/jax-mealkit`

Individual image repos such as `ghcr.io/nvidia/t5x` will be deprecated.

The flow of container tag information goes as follows:
```
CI:multi-arch.publish
^
CI:multi-arch.make-publish-configs.outputs.DOCKER_TAGS
^
CI:single-arch.outputs.DOCKER_TAGS
^
CI:single-arch.jobs.collect-docker-tags.outputs.TAGS
^
build-xyz.outputs.DOCKER_TAG_[MEALKIT|FINAL]
```

**Follow-up work:**
- [ ] add warning to redirect users to the new tags.

### CODE REVIEW

**Comment by yhtang** [comment]
I just realized that I need to update the BASE_IMAGE defaults in the dockerfiles, but at least it won't affect builds when running in CI as we always feed explicit base image values. Will fix tomorrow.

**Comment by nouiz** [comment]
From the description, the upstream container won't be accesible anymore?

**Comment by yhtang** [comment]
> From the description, the upstream container won't be accesible anymore?

Yes they are still accessible as `ghcr.io/nvidia/jax:upstream-t5x` etc. They were part of the `...` in the opening description as I was feeling a bit lazy to type them all 😁 
I'll updated the description to include the full set.

**Comment by terrykong** [comment]
Are you planning on migrating the old containers to this new naming scheme?

**Comment by yhtang** [comment]
> Are you planning on migrating the old containers to this new naming scheme?

Sure we can do that.

**Review by terrykong — APPROVED** [review]
Lgtm

**Pull request merged**
