### PR TITLE
Merges rosetta unit tests and takes off the marker which spun up another matrix job

### PR DESCRIPTION
**Pull request by terrykong**
This should simplify the rosetta tests and save some time since another matrix job was started for one test

### CODE REVIEW

**Review by yhtang — APPROVED** [review]
LGTM

**Comment by terrykong** [comment]
Running manually since CI not stable: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/6787945124

Will merge if no unknown error

**Comment by terrykong** [comment]
@ashors1 The ViT tests in the manual run looks like an OOM error for 8G1N and 8G2N. Is that expected?

**Comment by ashors1** [comment]
> @ashors1 The ViT tests in the manual run looks like an OOM error for 8G1N and 8G2N. Is that expected?

Yes, those OOMs are also caused by the known [XLA bug](https://github.com/openxla/xla/commit/8422226150968965613e6d998f0dd0cff1b9abfe).

**Pull request merged**
