### PR TITLE
Add mgmn workflow to PAX Rosetta

### PR DESCRIPTION
**Pull request by maanug-nv**
- Adds pax MGMN tests (`_test_pax.yaml`) to Rosetta PAX build and test workflow
- Routes pass/fail status of completion, perf, loss to badge and workflow output
- add error message to asserts for perf+loss tests

### CODE REVIEW

**Review by yhtang — DISMISSED** [review]
LGTM

**Comment by maanug-nv** [comment]
Yeah, I can click merge now that you have approved

**Comment by maanug-nv** [comment]
added one more thing, new badge was missing in README

**Review by terrykong — APPROVED** [review]
LGTM

**Comment by maanug-nv** [comment]
'resource not found' on the README should be fixed when a new run of rosetta pax is launched from main branch

**Pull request merged**
