### PR TITLE
Collect recursively and filter GPU tests using `jax_test_gpu` tag

### PR DESCRIPTION
**Pull request by andportnoy**

### CODE REVIEW

**Comment by andportnoy** [comment]
Needs https://github.com/jax-ml/jax/pull/24218.

**Comment by andportnoy** [comment]
Yeah this confuses me because the errors that I see are all of the form
```
RuntimeError: Backend 'tpu' failed to initialize: INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory. Available backends are ['cpu', 'cuda']
```
in tests like `//tests:blocked_sampler_test_tpu`. But one would think these tests shouldn't be collected when filtering with `--test_tag_filters=jax_test_gpu"`...

**Comment by andportnoy** [comment]
The full command is
```
bazel test --//jax:build_jaxlib=false //tests/... --test_tag_filters=jax_test_gpu --@local_config_cuda//:enable_cuda --cache_test_results=no --test_timeout=600 --test_tag_filters=-multiaccelerator --test_env=JAX_SKIP_SLOW_TESTS=1 --test_env=JAX_ACCELERATOR_COUNT=8 --test_env=XLA_PYTHON_CLIENT_ALLOCATOR=platform --test_env=XLA_PYTHON_CLIENT_PREALLOCATE=false --test_output=errors --java_runtime_version=remotejdk_11 --run_under /opt/jax/build/parallel_accelerator_execute.sh --local_test_jobs=64 --test_env=JAX_TESTS_PER_ACCELERATOR=8 --test_env=JAX_EXCLUDE_TEST_TARGETS=PmapTest.testSizeOverflow
```
I wonder if `--test_tag_filters` cannot be repeated and so `--test_tag_filters=-multiaccelerator` overrides `--test_tag_filters=jax_test_gpu`?

**Review by yhtang — APPROVED** [review]

**Comment by andportnoy** [comment]
https://github.com/jax-ml/jax/pull/24322 fixes `//tests/mosaic:flash_attention_gpu` on V100/A100.

**Review by olupton — APPROVED** [review]
LGTM
`//tests/mosaic:flash_attention_gpu` is failing, but I don't think that should block merging this

**Comment by andportnoy** [comment]
> `//tests/mosaic:flash_attention_gpu` is failing

Fixed in https://github.com/jax-ml/jax/pull/24467.

**Pull request merged**
